### ISSUE TITLE
xxx Not recognized as an internal or external command when using setup.cmd

### ISSUE THREAD

**Issue by ghyujkilop** [yoroshikun/node-pck-audio-extractor#2]
I tried running as admin and still no fix. any ideas?

Full cmd prompt:
"Installing deps, this may take a little while..."
'yarn' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
'yarn' is not recognized as an internal or external command,
operable program or batch file.
'node' is not recognized as an internal or external command,
operable program or batch file.

The system cannot find the file specified.
"Completed installing deps, you may now run 'decode.cmd' to start decoding audio!"
Press any key to continue . . .

I then try using decode.cmd but nothing happens to my .pck files (in input folder).

**Comment by yoroshikun** [comment]
As stated in the requirements section you need to install things like, yarn git and node on your own to run this.
https://github.com/yoroshikun/node-pck-audio-extractor#requirements
Once those are installed correctly the program should work fine.
